import "../styles/globals.scss";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import Head from "next/head";
import { auth } from "../firebase/firebaseConfig";
import { useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import LoginForm from "../src/components/LoginForm/LoginForm";
import Loading from "../src/components/Loading/Loading";

export default function App({ Component, pageProps }: AppProps) {
  ///////////  Logica de auth  ///////////
  const [authUser, setAuthUser] = useState<string | undefined>(undefined);
  const [load, setLoad] = useState(true);

  onAuthStateChanged(auth, (user) => {
    if (user) {
      // User is signed in, see docs for a list of available properties
      // https://firebase.google.com/docs/reference/js/firebase.User
      const uid = user.uid;
      // ...
      setAuthUser(uid);
      setLoad(false);
    } else {
      // User is signed out
      // ...
      setAuthUser(undefined);
      setLoad(false);
    }
  });
  console.log(auth);
  ////////////////////////////////////////
  //////////////// Render ////////////////////////
  function render() {
    return authUser ? <Component {...pageProps} /> : <LoginForm />;
  }
  ////////////////////////////////////////////////
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Create Next App</title>
      </Head>

      {load ? <Loading  />  : render()}
    </>
  );
}
