// import "../src/styles/globals.scss";
// import "../src/styles/backgrounds.scss";
// import "../src/styles/swal.scss";
// import type { AppProps } from "next/app";
// import Head from "next/head";
// import { auth } from "../firebase/firebaseConfig";
// import { useState } from "react";
// import { onAuthStateChanged } from "firebase/auth";
// import LoginForm from "../src/components/LoginForm/LoginForm";
// import Loading from "../src/components/Loading/Loading";
// import Navbar from "../src/components/Navbar/Navbar";

// export default function App({ Component, pageProps }: AppProps) {
//   ///////////  Logica de auth  ///////////

//   // console.log(auth);
//   ////////////////////////////////////////
//   //////////////// Render ////////////////////////

//   ////////////////////////////////////////////////
//   return (
//     <>
//       <Head>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/aptitud.png" />
//         <title>Cuotas Indomito</title>
//       </Head>

//       <Component {...pageProps} />
//     </>
//   );
// }
