import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { addUser } from "../firebase/cloudFirestore/addUser";
// import { useAppSelector, useAppDispatch } from "../redux/hooks";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  ///////////  Redux Count  ///////////

  //////////////////////////////////
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="@sweetalert2/themes/dark/dark.css" />
        <script src="sweetalert2/dist/sweetalert2.min.js"></script>
      </Head>
      <main className={styles.main}>
        {/* <button onClick={(e) => addUser()}>agregar comnpa</button> */}

        <Link href={"/gym"}>Gym</Link>
      </main>
    </>
  );
}
